if(NOT DYNLIBUTILS_DIR)
	message(FATAL_ERROR "DYNLIBUTILS_DIR is empty")
endif()

set(DYNLIBUTILS_BINARY_DIR "memory_utils")

set(DYNLIBUTILS_INCLUDE_DIR
	${DYNLIBUTILS_DIR}/include
)

set(DYNLIBUTILS_COMPILE_DEFINITIONS)

if(LINUX)
	set(DYNLIBUTILS_COMPILE_DEFINITIONS
		${DYNLIBUTILS_COMPILE_DEFINITIONS}
		-D_GLIBCXX_USE_CXX11_ABI=0
	)
endif()

add_subdirectory(${DYNLIBUTILS_DIR} ${DYNLIBUTILS_BINARY_DIR})
target_compile_definitions(${DYNLIBUTILS_BINARY_DIR} PRIVATE ${DYNLIBUTILS_COMPILE_DEFINITIONS})
