name: Build on Windows

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**.yml'
      - 'cmake/**'
      - 'external/**'
      - 'src/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'trigger-build.txt'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**.yml'
      - 'cmake/**'
      - 'external/**'
      - 'src/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'trigger-build.txt'

env:
  CMAKE_RELEASE_PRESET_NAME: Windows/Release
  CMAKE_RELEASE_PRESET_PUBLIC_NAME: Release
  CMAKE_RELEASE_CONFIG_NAME: Release
  CMAKE_RELEASE_OUTPUT_PATTERN: build/Windows/Release/Release/*
  CL_CC: cl
  CL_CXX: cl
  HL2SDK_BRANCH: cs2
  HL2SDK_ROOT: external\hl2sdk-cs2
  MMSOURCE_ROOT: external\metamod-source

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Set up environment variables
      run: |
        echo "REPOSITORY_NAME=$(basename ${env:GITHUB_REPOSITORY})" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "ABSOLUTE_PATH=${env:GITHUB_WORKSPACE}" | Out-File -FilePath $env:GITHUB_ENV -Append
      shell: pwsh

    - name: Configure Git to treat current directory as safe
      run: git config --global --add safe.directory $env:GITHUB_WORKSPACE
      shell: pwsh

    - name: Get latest tag
      id: get-latest-tag
      run: |
        if ((git tag) -eq $null) {
          echo "No tags found"
          echo "LATEST_TAG=none" | Out-File -FilePath $env:GITHUB_ENV -Append
        } else {
          $LATEST_TAG = git describe --tags (git rev-list --tags --max-count=1)
          echo "LATEST_TAG=$LATEST_TAG" | Out-File -FilePath $env:GITHUB_ENV -Append
        }
      shell: pwsh

    - name: Checkout HL2SDK
      uses: actions/checkout@v4
      with:
        repository: Wend4r/hl2sdk
        ref: ${{ env.HL2SDK_BRANCH }}
        fetch-depth: 1
        path: ${{ env.HL2SDK_ROOT }}

    - name: Checkout MetaMod:Source
      uses: actions/checkout@v4
      with:
        repository: alliedmodders/metamod-source
        fetch-depth: 1
        path: ${{ env.MMSOURCE_ROOT }}

    - name: Release - Configure CMake
      run: >
        cmake --preset ${{ env.CMAKE_RELEASE_PRESET_NAME }}
        -DCMAKE_C_COMPILER=${{ env.CL_CC }}
        -DCMAKE_CXX_COMPILER=${{ env.CL_CXX }}
        -DSOURCESDK_DIR=${{ env.ABSOLUTE_PATH }}\${{ env.HL2SDK_ROOT }}
        -DMETAMOD_DIR=${{ env.ABSOLUTE_PATH }}\${{ env.MMSOURCE_ROOT }}

    - name: Release - Build
      run: cmake --build --preset ${{ env.CMAKE_RELEASE_PRESET_NAME }} --parallel --config ${{ env.CMAKE_RELEASE_CONFIG_NAME }}

    - name: Release - Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.REPOSITORY_NAME }}-${{ env.LATEST_TAG }}-${{ runner.os }}_${{ env.CMAKE_RELEASE_PRESET_PUBLIC_NAME }}
        path: ${{ env.CMAKE_RELEASE_OUTPUT_PATTERN }}
